build:
  image: python:2
  commands:
    - env
    - curl https://api.ciscospark.com/v1/messages -X POST -H "Authorization:Bearer $$SPARK_TOKEN" --data "roomId=$$SPARK_ROOM" --data "text=Repo $CI_REPO - Drone kicking off build $CI_BUILD_NUMBER"



